export const clientsData = [
  {
    name: "Abhishek",
    company: "Karmarth IP",
    address: "Greater Noida",
    mobile: "999999999",
    email: "abc@gmail.com",
    source: "facebook",
    total_Amt_Received: 20000,
    services: [
      {
        id: 1,
        type: "Website Development",
        costing: 12000,
        oneTime_Monthly: "oneTime",
        started_date: "21-12-2021",
        finish_date: "14.12.2021",
        advance: 5000,
        other_payments: 2000,
        pending: 10000,
        isCompleted: true,
      },
      {
        id: 2,
        type: "Digital Marketing",
        costing: 12000,
        oneTime_Monthly: "oneTime",
        started_date: "21-12-2021",
        finish_date: "14.12.2021",
        advance: 5000,
        other_payments: 2000,
        pending: 10000,
        isCompleted: true,
      },
    ],
    third_party_portals: [
      {
          portal_id: 1,
        portal: "Domain",
        name: "www.karmarthIP",
        service_provider: "Godaddy",
        reg_Amt: 1200,
        reg_Date: "11.12.2021",
        renew_Amt: 1600,
        exp_date: "12.12.1212",
      },
      {
        portal_id: 2,
        portal: "Hosting",
        name: "Simple",
        service_provider: "Godaddy",
        reg_Amt: 1200,
        reg_Date: "11.12.2021",
        renew_Amt: 1600,
        exp_date: "12.12.1212",
      },
      {
        portal_id: 3,
        portal: "Email",
        name: "karmarthIP@gmail.com",
        service_provider: "Godaddy",
        reg_Amt: 1200,
        reg_Date: "11.12.2021",
        renew_Amt: 1600,
        exp_date: "12.12.1212",
      },
    ],
  },
];
